#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Dec 12 15:37:22 2018

@author: kebaili
"""
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split

from sklearn import datasets, linear_model
def exploredata():
 pd.options.display.float_format = '{:.2f}'.format 
 df = pd.read_csv('goodbooks-10k/ratings.csv', sep=',', names=['user_id','book_id','rating'])
 print(df.shape)
 print(df.head())
 print(df.describe())
 
 r = pd.read_csv( 'goodbooks-10k/ratings.csv' )
 print(r.shape)
 print(r.describe())
 
 books = pd.read_csv( 'goodbooks-10k/books.csv' )
 print(books.shape)
 print(books.describe())
   
   
 ratingsperbook = pd.DataFrame(df.groupby('book_id')['rating'].mean())
 print(ratingsperbook.head())
 
 
 ratingsperuser = pd.DataFrame(df.groupby('user_id')['rating'].mean())
 print(ratingsperuser.head())
 
 df['number_of_ratings'] = df['book_id'].value_counts()

 sns.jointplot(x="rating", y="number_of_ratings", data=df)# graphe globale illustrant la distribution des votes
 
 book_matrix = df.pivot_table(index='user_id', columns='book_id', values='rating')
 print('pivot',book_matrix.head())
 
 df['rating'].hist(bins=5)
 y=df.rating
 X_train, X_test, y_train, y_test = train_test_split(df, y, test_size=0.2)
 print (X_train.shape, y_train.shape)
 print (X_test.shape, y_test.shape)
 
exploredata()